config/routes.rb
Rails.application.routes.draw do
  root :to => "orders#index"
  resources :loyalty_plans, only: [:index]
  resources :customers, only: [:index, :show, :create]
  resources :devices, only: [:index, :create]
  resources :offers, only: [:index, :create]
  resources :orders, only: [:index, :create]

  resources :customers do
    scope module: :customers do
      resources :devices, only: [:index]
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/customer.rb
class Customer < ApplicationRecord
  validates :document, :email, :name, presence: true
  validates :email, :document, uniqueness: true

  after_create :set_score
  has_many :orders
  has_many :devices
  
  private

  def set_score
    update(score: 'E')
  end
end

app/models/cutomer.rb
class Customer < ApplicationRecord
  validates_presence_of :document, :email, :name

  has_many :orders
  has_many :devices
end

app/models/device.rb
class Device < ApplicationRecord
  validates_presence_of :model, :imei
  validates :imei, uniqueness: true

  belongs_to :customer
end

app/models/loyalty_plan.rb
class LoyaltyPlan < ApplicationRecord
end

app/models/offer.rb
class Offer < ApplicationRecord
  has_many :orders
end

app/models/order.rb
class Order < ApplicationRecord
  SCORES = {
    3 => 'B',
    2 => 'C',
    1 => 'D',
    0 => 'E'
  }

  belongs_to :customer
  belongs_to :device
  belongs_to :offer
  belongs_to :loyalty_plan

  after_create :update_customer_score

  def installment
    ((offer.annual_value * (1 - (loyalty_plan.rate / 100))) / period).round(2)
  end

  private
 
  def update_customer_score
    total_orders = customer.orders.count
    score = ( total_orders > 3) ? 'A' : SCORES[total_orders]
    customer.update(score: score)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/customers/devices_controller.rb
class Customers::DevicesController < ApplicationController
  def index
    render json: Device.where(customer_id: params[:customer_id]).order(:manufacturer)
  rescue => e
    flash[:alert] = e.message
    redirect_back(fallback_location: root_path)
  end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  def index
    @customer = Customer.all
  rescue => e
    flash[:alert] = e.message
    redirect_back(fallback_location: root_path)
  end

  def show
    render json: Customer.find_by(document: params['id'])
  end

  def create
    Customer.create(item_params)

    redirect_back(fallback_location: root_path)
  rescue => e
    flash[:alert] = e.message
    redirect_back(fallback_location: root_path)
  end

  private

  def item_params
    {
      name: params['name'],
      document: params['document'],
      email: params['email']
    }
  end
end

app/controllers/devices_controller.rb
class DevicesController < ApplicationController
  def index
    @devices = Device.all.order(:id)
  rescue => e
    flash[:alert] = e.message
    redirect_back(fallback_location: root_path)
  end

  def create
    Device.create(device_params)

    redirect_back(fallback_location: root_path)
  rescue => e
    flash[:alert] = e.message
    redirect_back(fallback_location: root_path)
  end

  private

  def device_params
    {
      manufacturer: params[:manufacturer],
      model: params[:model],
      imei: params[:imei],
      customer_id: params[:customer_id]
    }
  end
end

app/controllers/loyalty_plans_controller.rb
class LoyaltyPlansController < ApplicationController
  def index
    @loyalty_plans = LoyaltyPlan.all.order(:id)
  rescue => e
    flash[:alert] = e.message
    redirect_back(fallback_location: root_path)
  end
end

app/controllers/offers_controller.rb
class OffersController < ApplicationController
  def index
    @offers = Offer.all.order(:id)
  rescue => e
    flash[:alert] = e.message
    redirect_back(fallback_location: root_path)
  end

  def create
    Offer.create(annual_value: params['annual_value'])

    redirect_back(fallback_location: root_path)
  rescue => e
    flash[:alert] = e.message
    redirect_back(fallback_location: root_path)
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def index
    orders = Order.all.order(:id)

    @orders_presenter = orders.map{ |o| OrderPresenter.new(o) }
  rescue => e
    flash[:alert] = e.message
    redirect_back(fallback_location: root_path)
  end

  def create
    order = OrderBuilder.new(orders_params).build

    order.save! ? (redirect_back(fallback_location: root_path)) : (head :unprocessable_entity)
  rescue => e
    flash[:alert] = "Não foi possível processar sua solicitaçao. ERRO: #{e.message}"
    redirect_back(fallback_location: root_path)
  end

  private
  
  def orders_params
    {
      period: params[:period],
      customer_id: params[:customer_id],
      device_id: params[:device_id],
      offer_id: params[:offer_id]
    }
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def dispatcher_route
    "#{controller_path.gsub(/\//, "_")}##{action_name}"
  end
end

app/helpers/customers_helper.rb
module CustomersHelper

end

app/helpers/devices_helper.rb
module DevicesHelper
  def options_for_device_select
    options_for_select(
      customer.devices.order(:id).map{ |c| ["#{c.model}","#{c.id}"]}
    )
  end
end

app/helpers/offers_helper.rb
module OffersHelper
  def options_for_offer_select
    options_for_select(
      Offer.all.map{ |o| ["#{o.annual_value}","#{o.id}"]}
    )
  end
end

app/views/customers/_modal_block.html.erb
<div class="modal" id="customer-form">
  <div class="modal-dialog modal-md">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      </div>
      <div class="modal-body">
        <%= form_tag customers_path, method: :post, class: 'form-horizontal' do %>
          <div class="form-group">
            <div class="col-sm-12">
              <%= label_tag :name, 'Nome', class: 'col-xs-6' %>
              <%= text_field_tag :name, '', class: 'form-control', placeholder: 'Digite o nome do cleinte', required: true %>
            </div>
            <div class="col-sm-12">
              <%= label_tag :document, 'CPF', class: 'col-xs-6' %>
              <%= text_field_tag :document, '', class: 'form-control', placeholder: 'Digite o CPF do cliente', required: true %>
            </div>
            <div class="col-sm-12">
            <%= label_tag :email, 'Email', class: 'col-xs-6' %>
              <%= text_field_tag :email, '', class: 'form-control', placeholder: 'Digite o email do cliente', required: true %>
            </div>
          </div>
          <%= submit_tag 'Salvar', class: 'btn btn-sm btn-primary pull-right' %>
        <% end %>
        <div class="clearfix"></div>
      </div>
    </div>
  </div>
</div>

app/views/customers/index.html.erb
<div class="content content-boxed">
  <div class="block">
    <div class="block-header bg-gray-lighter">
      <div class="col-sm-12">
        <div class="col-sm-6">
          <h3 class="block-title ">Clientes</h3>
        </div>
        <div class="col-sm-6">
          <button class="btn btn-sm btn-primary pull-right" data-toggle="modal" data-target="#customer-form" type="button"><i class="fa fa-plus"></i></button>
        </div>
      </div>
    </div>
    <div class="block-content">
      <table class="table table-borderless table-striped table-vcenter">
        <thead>
          <tr>
            <th class="text-center">Nome</th>
            <th class="text-center">Score</th>
            <th class="text-center">CPF</th>
            <th class="text-center">Email</th>
          </tr>
        </thead>
        <tbody>
          <% @customer.each do |customer| %>
            <tr>
              <td class="text-center"> <%= customer.name.capitalize %> </td>
              <td class="text-center"> <%= customer.score %> </td>
              <td class="text-center"> <%= customer.document %> </td>
              <td class="text-center"> <%= customer.email %> </td>
            </tr>
          <% end if @customer %>
        </tbody>
      </table>
    </div>
  </div>
</div>
<%= render 'modal_block' %>

app/views/devices/_device_behavior.html.erb
<script>
  $("#btn-search-customer").on("click", function() {
    var customerDocument = $("#input-customer-document").val();
    $.ajax({
      url: "customers/" + customerDocument,
      success: function(result) {
        if (result !== null ) {
          $(".customer-name").text(result.name);
          $(".customer-document").text(result.document);
          $(".customer-email").text(result.email);
          $("#customer_id").val(result.id);
        }else{
          alert("Cliente não encontrado");
        }
      }
    });
  });
</script>

app/views/devices/_modal_block.html.erb
<div class="modal" id="device-form">
  <div class="modal-dialog modal-md">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      </div>
      <div class="modal-body">
        <%= form_tag devices_path, method: :post, class: 'form-horizontal' do %>
          <div class="form-group">
      
            <div class="col-sm-12">
              <%= label_tag '', 'Pesquisar cliente' %>
              <div class="input-group">
                <%= text_field_tag :customer, '', id: 'input-customer-document', class: 'form-control', placeholder: 'Digite o cpf do cliente', required: true %>
                <div class="input-group-addon  btn btn-sm btn-primary"  type="button" id="btn-search-customer">
                  <span class="fa fa-search "></span>
                </div>
              </div>
            </div>

            <div class="col-sm-12">
              <div class='block'>
                <div class="col-sm-12">
                  <h5>Nome: <%= label_tag 'customer-name', '', class: 'customer-name' %></h5>
                </div>
                <div class="col-sm-12">
                  <h5>CPF: <%= label_tag 'customer-document', '', class: 'customer-document' %></h5>
                </div>
                <div class="col-sm-12">
                  <h5>Email: <%= label_tag 'customer-email', '', class: 'customer-email' %></h5>
                </div>
                <%= hidden_field_tag 'customer_id' %>
              </div>
            </div>

            <div class="col-sm-12">
              <%= label_tag :manufacturer, 'Fabricante', class: 'col-xs-6' %>
              <%= text_field_tag :manufacturer, '', class: 'form-control', placeholder: 'Digite o fabricante do aparelho a ser cadastrado', required: true %>
            </div>
            <div class="col-sm-12">
              <%= label_tag :model, 'Model', class: 'col-xs-6' %>
              <%= text_field_tag :model, '', class: 'form-control', placeholder: 'Digite o modelo do aparelho a ser cadastrado', required: true %>
            </div>
            <div class="col-sm-12">
              <%= label_tag :imei, 'IMEI', class: 'col-xs-6' %>
              <%= text_field_tag :imei, '', class: 'form-control', placeholder: 'Digite o IMEI do aparelho a ser cadastrado', required: true %>
            </div>
          </div>
          <%= submit_tag 'Salvar', class: 'btn btn-sm btn-primary pull-right' %>
        <% end %>
        <div class="clearfix"></div>
      </div>
    </div>
  </div>
</div>
<%= render 'device_behavior' %>

app/views/devices/index.html.erb
<div class="content content-boxed">
  <div class="block">
    <div class="block-header bg-gray-lighter">
      <div class="col-sm-12">
        <div class="col-sm-6">
          <h3 class="block-title ">Aparelhos</h3>
        </div>
        <div class="col-sm-6">
          <button class="btn btn-sm btn-primary pull-right" data-toggle="modal" data-target="#device-form" type="button"><i class="fa fa-plus"></i></button>
        </div>
      </div>
    </div>

    <div class="block-content">
      <table class="table table-borderless table-striped table-vcenter">
        <thead>
          <tr>
            <th class="text-center">Id</th>
            <th class="text-center">Cliente</th>
            <th class="text-center">Fabricante</th>
            <th class="text-center">Modelo</th>
            <th class="text-center">IMEI</th>
          </tr>
        </thead>
        <tbody>
          <% @devices.each do |device| %>
            <tr>
              <td class="text-center"> <%= device.id %> </td>
              <td class="text-center"> <%= device.customer.name.capitalize %> </td>
              <td class="text-center"> <%= device.manufacturer %> </td>
              <td class="text-center"> <%= device.model %> </td>
              <td class="text-center"> <%= device.imei %> </td>
            </tr>
          <% end if @devices %>
        </tbody>
      </table>
    </div>
  </div>
</div>
<%= render 'modal_block' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Divs</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" />
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <div class="navbar-class">
      <div class="container">
        <ul class="nav navbar-nav">
          <li><%=link_to "Seguros", orders_path%></li>
          <li><%=link_to "Planos", offers_path %></li>
          <li><%=link_to "Descontos", loyalty_plans_path%></li>
          <li><%=link_to "Clientes", customers_path %></li>
          <li><%=link_to "Aparelhos", devices_path %></li>
        </ul>
      </div>
    </div>
  </head>

  <body>
    <% if notice %>
    <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
    <p class="alert alert-danger"><%= alert %></p>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/loyalty_plans/index.html.erb
<div class="content content-boxed">
  <div class="block">
    <div class="block-header bg-gray-lighter">
      <div class="col-sm-12">
        <div class="col-sm-6">
          <h3 class="block-title ">Descontos fidelidade</h3>
        </div>
      </div>
    </div>
    <div class="block-content">
      <table class="table table-borderless table-striped table-vcenter">
        <thead>
          <tr>
            <th class="text-center">Score</th>
            <th class="text-center">Desconto</th>
          </tr>
        </thead>
        <tbody>
          <% @loyalty_plans.each do |loyalty_plan| %>
            <tr>
              <td class="text-center"> <%= loyalty_plan.score %> </td>
              <td class="text-center"> <%= loyalty_plan.rate %> </td>
            </tr>
          <% end if @loyalty_plans  %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/offers/_modal_block.html.erb
<div class="modal" id="offer-form">
  <div class="modal-dialog modal-md">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      </div>
      <div class="modal-body">
        <%= form_tag offers_path, method: :post, class: 'form-horizontal' do %>
          <div class="form-group">
            <div class="col-sm-12">
              <%= label_tag :annual_value, 'Valor Anual', class: 'col-xs-6' %>
              <%= number_field_tag :annual_value, '', class: 'form-control', placeholder: 'Digite o valor anual a ser cadastrado', required: true %>
            </div>
          </div>
          <%= submit_tag 'Salvar', class: 'btn btn-sm btn-primary pull-right' %>
        <% end %>
        <div class="clearfix"></div>
      </div>
    </div>
  </div>
</div>

app/views/offers/index.html.erb
<div class="content content-boxed">
  <div class="block">
    <div class="block-header bg-gray-lighter">
      <div class="col-sm-12">
        <div class="col-sm-6">
          <h3 class="block-title ">Planos oferecidos</h3>
        </div>
        <div class="col-sm-6">
          <button class="btn btn-sm btn-primary pull-right" data-toggle="modal" data-target="#offer-form" type="button"><i class="fa fa-plus"></i></button>
        </div>
      </div>
    </div>
    <div class="block-content">
      <table class="table table-borderless table-striped table-vcenter">
        <thead>
          <tr>
            <th class="text-center">Valor anual</th>
          </tr>
        </thead>
        <tbody>
          <% @offers.each do |offer | %>
            <tr>
              <td class="text-center"> <%= number_to_currency(offer.annual_value) %> </td>
            </tr>
          <% end if @offers %>
        </tbody>
      </table>
    </div>
  </div>
</div>
<%= render 'modal_block' %>

app/views/orders/_modal_block.html.erb
<div class="modal" id="order-form">
  <div class="modal-dialog modal-md">
    <div class="modal-content">
      <div class="modal-header ">
        <button type="button" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      </div>
      <div class="modal-body">
        <%= form_tag orders_path, method: :post, class: 'add-order-form form-horizontal' do %>
          <div class="form-group">
            <div class="col-sm-12">
              <%= label_tag '', 'Pesquisar cliente' %>
              <div class="input-group">
                <%= text_field_tag :customer, '', id: 'input-customer-document', class: 'form-control', placeholder: 'Digite o cpf do cliente', required: true %>
                <div class="input-group-addon  btn btn-sm btn-primary"  type="button" id="btn-search-customer">
                  <span class="fa fa-search "></span>
                </div>
              </div>
            </div>
            <div class="col-sm-12">
              <div class='block'>
                <div class="col-sm-12">
                  <h5>Nome: <%= label_tag 'customer-name', '', class: 'customer-name' %></h5>
                </div>
                <div class="col-sm-12">
                  <h5>CPF: <%= label_tag 'customer-document', '', class: 'customer-document' %></h5>
                </div>
                <div class="col-sm-12">
                  <h5>Email: <%= label_tag 'customer-email', '', class: 'customer-email' %></h5>
                </div>
                <%= hidden_field_tag 'customer_id' %>
                <div class="col-sm-12">
                  <%= label_tag :device, 'Aparelho' %>
                  <%= select_tag :device_id, '', class: 'form-control', id: 'select-device', required: true, include_blank: '' %>
                </div>
              </div>
            </div>
            <div class="col-sm-12">
              <%= label_tag :size, 'Planos' %>
              <%= select_tag :offer_id, options_for_offer_select, class: 'form-control', id: 'offer-select', required: true, include_blank: '' %>
            </div>
            <div class="col-sm-12">
              <%= label_tag :period, 'Período' %>
              <%= number_field_tag :period, '',max:12, class: 'form-control', placeholder: 'Digite qtas vezes deseja', required: true %>
            </div>
          </div>
        <%= submit_tag 'Salvar', class: 'btn btn-sm btn-primary pull-right' %>
        <% end %>
        <div class="clearfix"></div>
      </div>
    </div>
  </div>
</div>
<%= render 'order_behavior' %>

app/views/orders/_order_behavior.html.erb
<script>
$("#btn-search-customer").on("click", function() {
    var customerDocument = $("#input-customer-document").val();
    $.ajax({
      url: "customers/" + customerDocument,
      success: function(result) {
        if (result !== null ) {
          $(".customer-name").text(result.name);
          $(".customer-document").text(result.document);
          $(".customer-email").text(result.email);
          $("#customer_id").val(result.id);
          fillSelectDevice(result.id)
        }else{
          alert("Cliente não encontrado");
        }
      }
    });
  });

  function fillSelectDevice(customerId) {
    $.ajax({
      type: 'GET',
      url: 'customers/' + customerId + '/devices',
      success: function(data) {
        devices = data;
        $.each(devices, function(id, device) {
          $("#select-device").append($('<option>', {
            value: device.id,
            text: ("Imei: " + device.imei)
          }));
        });
      }
    });
  };
</script>

app/views/orders/index.html.erb
<div class="content content-boxed">
  <div class="block">
    <div class="block-header bg-gray-lighter">
      <div class="col-sm-12">
        <div class="col-sm-6">
          <h3 class="block-title ">Seguros contratados</h3>
        </div>
        <div class="col-sm-6">
          <button class="btn btn-sm btn-primary pull-right" data-toggle="modal" data-target="#order-form" type="button"><i class="fa fa-plus"></i></button>
        </div>
      </div>
    </div>
    <div class="block-content">
      <table class="table table-borderless table-striped table-vcenter">
        <thead>
          <tr>
            <th class="text-center">Cliente</th>
            <th class="text-center">Score</th>
            <th class="text-center">Fabricante</th>
            <th class="text-center">Modelo</th>
            <th class="text-center">IMEI</th>
            <th class="text-center">Plano</th>
            <th class="text-center">Desconto</th>
            <th class="text-center">Período</th>
            <th class="text-center">Parcelas</th>
          </tr>
        </thead>
        <tbody>
          <% @orders_presenter.each do |order| %>
            <tr>
              <td class="text-center"> <%= order.customer_name %> </td>
              <td class="text-center"> <%= order.customer_score %> </td>
              <td class="text-center"> <%= order.device_manufacturer %> </td>
              <td class="text-center"> <%= order.device_model %> </td>
              <td class="text-center"> <%= order.device_imei %> </td>
              <td class="text-center"> <%= number_to_currency(order.offer_annual_value) %> </td>
              <td class="text-center"> <%= order.loyalty_plan_rate %> </td>
              <td class="text-center"> <%= order.period %> </td>
              <td class="text-center"> <%= number_to_currency(order.installment) %> </td>
            </tr>
          <% end if @orders_presenter %>
        </tbody>
      </table>
    </div>
  </div>
</div>
<%= render 'modal_block' %>